version: '3'

networks:
  intelmq-network:
    driver: bridge

services:
  intelmq:
    build: intelmq/
    ports:
        - 8081:80
    depends_on:
      - redis
    image: intelmq
    networks:
      - intelmq-network
    volumes:
      - ./intelmq/intelmq-bots/output/:/opt/intelmq/var/lib/bots/file-output/
      - ./intelmq/intelmq-bots/etc:/opt/intelmq/etc
      - ./intelmq/intelmq-bots/bots:/opt/dev_intelmq/intelmq/bots/
    environment:
      - REDIS_SERVER=redis 
  redis:
    image: redis
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf
    networks:
      - intelmq-network
