version: '2'
volumes:
  cert-intelmq-bots-output:
    driver: local
  cert-intelmq-bots:
    driver: local
services:
  redis:
    image: redis
    volumes:
    - ./redis:/usr/local/etc/redis/
    command:
    - redis-server
    - /usr/local/etc/redis/redis.conf
  intelmq:
    image: certunlp/intelmq:1.0
    environment:
      REDIS_SERVER: redis
      REPO_UPDATE: https://github.com/CERTUNLP/intelmq-bots.git
    volumes:
    - cert-intelmq-bots-output:/opt/intelmq/var/lib/bots/file-output/
    - cert-intelmq-bots:/opt/intelmq/etc
    links:
    - redis:redis
    ports:
        - 8081:80
