version: '3'

networks:
  intelmq-network:
    driver: bridge

services:
  intelmq:
    build: intelmq/
    ports:
        - 8081:80
    depends_on:
      - redis
    networks:
      - intelmq-network
    volumes:
      - ./volumes/output/:/opt/intelmq/var/lib/bots/file-output/
      - ./volumes/logs:/opt/intelmq/var/log/
      # git clone yourRepo volumes/intelmq-bots git clone https://github.com/CERTUNLP/intelmq-bots.git volumes/intelmq-bots
      - ./volumes/intelmq-bots/etc:/opt/intelmq/etc
      - ./volumes/intelmq-bots/bots/BOTS:/opt/intelmq/etc/BOTS
      - ./volumes/intelmq-bots/:/intelmq-bots/
    environment:
      REDIS_SERVER: redis
      DEV: "true"
      LOG_MAIL_ENABLED: "true"
      LOG_MAIL_MAILHOST: "mail.example.unlp.edu.ar"
      LOG_MAIL_PORT: 25
      LOG_MAIL_FROMADDR: "intelmq@examplefeeds.unlp.edu.ar"
      LOG_MAIL_TOADDR: "support@example.unlp.edu.ar"
      LOG_MAIL_SUBJECT: "[INTELMQ] Application Error"
  redis:
    image: redis
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf
    networks:
      - intelmq-network
  logrotate:
    image: blacklabelops/logrotate
    environment:
      LOGS_DIRECTORIES: /var/log/intelmq
      LOGROTATE_COPIES: '3'
      LOGROTATE_SIZE: 100M
      LOGROTATE_COMPRESSION: compress
      LOGROTATE_CRONSCHEDULE: '46 * * * * *'
    volumes:
    - ./volumes/logs:/var/log/intelmq
