version: '3'

networks:
  intelmq-network:
    driver: bridge

services:
  intelmq:
    build: intelmq/
    ports:
        - 8081:80
    depends_on:
      - redis
    networks:
      - intelmq-network
    volumes:
      - ./intelmq/intelmq-bots/output/:/opt/intelmq/var/lib/bots/file-output/
      - ./intelmq/intelmq-bots/logs:/opt/intelmq/var/log/
      # git clone yourRepo intelmq/intelmq-bots/gitRepo  or git clone https://github.com/CERTUNLP/intelmq-bots.git intelmq/intelmq-bots/gitRepo
      - ./intelmq/intelmq-bots/gitRepo/etc:/opt/intelmq/etc
      - ./intelmq/intelmq-bots/gitRepo/bots/BOTS:/opt/intelmq/etc/BOTS
      - ./intelmq/intelmq-bots/gitRepo:/intelmq-bots/
    environment:
      REDIS_SERVER: redis
      DEV: "true"
  redis:
    image: redis
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf
    networks:
      - intelmq-network
  logrotate:
    image: blacklabelops/logrotate
    environment:
      LOGS_DIRECTORIES: /var/log/intelmq
      LOGROTATE_COPIES: '3'
      LOGROTATE_SIZE: 100M
      LOGROTATE_COMPRESSION: compress
      LOGROTATE_CRONSCHEDULE: '46 * * * * *'
    volumes:
    - ./intelmq/intelmq-bots/logs:/var/log/intelmq

